services:
  slidev:
    image: node:20-alpine
    container_name: cos3103-slidev

    working_dir: /app/slides_src

    volumes:
      - ./slides_src:/app/slides_src
      - slidev_modules:/app/slides_src/node_modules

    ports:
      - "3030:3030"

    command: sh -c "npm ci && npm run cos3103"

    restart: unless-stopped

volumes:
  slidev_modules:
